# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16P3-c23qPYZWefg36J5jjajM6djj6MD8
"""

!pip install streamlit

import streamlit as st
import joblib
import pandas as pd
import numpy as np

# 1. Set Page Configuration (MUST be the first command)
st.set_page_config(page_title="Movie Popularity Predictor", page_icon="🎬", layout="centered")

# 2. Load the models downloaded from Colab
@st.cache_resource
def load_models():
    try:
        model = joblib.load('best_model.pkl')
        cv = joblib.load('vectorizer.pkl')
        scaler = joblib.load('scaler.pkl')
        return model, cv, scaler
    except Exception as e:
        st.error(f"Error: {e}. Please ensure 'best_model.pkl', 'vectorizer.pkl', and 'scaler.pkl' are uploaded to GitHub.")
        return None, None, None

model, cv, scaler = load_models()

# 3. App Header
st.title("🎬 Movie Popularity Predictor")
st.write("This app predicts the **Popularity Class** of a movie.")
st.divider()

# 4. User Inputs
st.subheader("📊 Enter Movie Features")

col1, col2 = st.columns(2)

with col1:
    vote_average = st.number_input("Vote Average", min_value=0.0, max_value=10.0, value=8.0, step=0.1)
    vote_count = st.number_input("Total Vote Count", min_value=0, max_value=50000, value=2148, step=10)

with col2:
    # We collect release year for the UI, but it won't be sent to the model to avoid errors
    release_year = st.slider("Release Year", min_value=1900, max_value=2026, value=2015)
    release_month = st.slider("Release Month", min_value=1, max_value=12, value=6)
    release_day = st.slider("Release Day", min_value=1, max_value=31, value=15)

st.divider()
st.subheader("📝 Movie Details")
movie_title = st.text_input("Movie Title", value="The Shawshank Redemption")
movie_overview = st.text_area("Overview", value="A movie about hope and freedom.")

# 5. Prediction Logic
if st.button("🔮 Predict Popularity", type="primary"):
    if model is not None:
        try:
            # Scale numeric features (Pass as DataFrame to match training format)
            num_df = pd.DataFrame([[vote_average, vote_count, 0]], columns=['vote_average', 'vote_count', 'popularity'])
            scaled = scaler.transform(num_df)
            vote_average_scaled = scaled[0][0]
            vote_count_scaled = scaled[0][1]

            # CountVectorizer on overview text
            overview_cv = cv.transform([movie_overview]).toarray()

            # Combine features (Release year is successfully removed here to match your 54 features)
            numeric_features = np.array([[vote_average_scaled, vote_count_scaled, release_month, release_day]])
            input_data_array = np.concatenate([numeric_features, overview_cv], axis=1)

            # Convert to DataFrame with correct column names (LightGBM requires this to prevent errors)
            feature_names = ['vote_average', 'vote_count', 'release_month', 'release_day'] + [f'overview_{i}' for i in range(50)]
            input_data = pd.DataFrame(input_data_array, columns=feature_names)

            # Predict the class
            prediction = model.predict(input_data)[0]

            st.divider()
            st.subheader("🎯 Prediction Results")

            # Display results based on the predicted class
            if prediction == 0:
                st.success("🟢 Low Popularity")
                st.write("📉 This movie is predicted to have **Low** popularity.")
            elif prediction == 1:
                st.warning("🟡 Medium Popularity")
                st.write("👍 This movie is predicted to have **Medium** popularity.")
            else:
                st.error("🔴 High Popularity")
                st.balloons()
                st.write("🌟 This movie is predicted to have **High** popularity!")

        except Exception as e:
            st.error(f"Prediction failed: {e}")