# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16P3-c23qPYZWefg36J5jjajM6djj6MD8
"""

app_code = '''
import streamlit as st
import joblib
import numpy as np

# Load model and tfidf
model = joblib.load("best_model.pkl")
tfidf = joblib.load("tfidf.pkl")

st.title("🎬 Movie Win or Flop Predictor")
st.write("Enter movie details below to predict:")

# Inputs
title    = st.text_input("Movie Title",
           "The Shawshank Redemption")
overview = st.text_area("Movie Overview",
           "A story about hope and freedom in prison.")
release_year  = st.number_input("Release Year",
                value=1994)
release_month = st.number_input("Release Month",
                value=9)
release_day   = st.number_input("Release Day",
                value=23)

if st.button("Predict"):
    # TF-IDF transform overview
    overview_vec = tfidf.transform([overview]).toarray()
    prediction   = model.predict(overview_vec)[0]

    st.subheader("Prediction Result:")
    if prediction == 1:
        st.success("🏆 WIN Movie!")
    else:
        st.error("❌ FLOP Movie!")
'''

with open('app.py', 'w') as f:
    f.write(app_code)
print("✅ app.py created!")
